const gallery = [
	{
		src: '/images/informativas/anuncio_versiones_anteriores.jpg',
		alt: 'Imagen anuncio de versiones anteriores',
		width: 1080,
		height: 1080,
		title: 'Anuncio de versiones anteriores',
	},
	{
		src: '/images/informativas/autorización_dian_pos_electrónico.jpg',
		alt: 'Imagen autorización DIAN POS electrónico',
		width: 1080,
		height: 1080,
		title: 'Autorización DIAN POS electrónico',
	},
	{
		src: '/images/informativas/cambio_de_identificación.jpg',
		alt: 'Imagen cambio de identificación',
		width: 1080,
		height: 1080,
		title: 'Cambio de identificación',
	},
	{
		src: '/images/informativas/correo_electrónico_spam.jpg',
		alt: 'Imagen correo electrónico spam',
		width: 1080,
		height: 1080,
		title: 'Correo electrónico spam',
	},
	{
		src: '/images/informativas/mensajes_software.jpg',
		alt: 'Imagen mensajes de software',
		width: 940,
		height: 788,
		title: 'Mensajes de software',
	},
	{
		src: '/images/informativas/notas_crédito_aceptadas_.jpg',
		alt: 'Imagen notas de crédito aceptadas',
		width: 940,
		height: 788,
		title: 'Notas de crédito aceptadas',
	},
	{
		src: '/images/informativas/novedades.jpg',
		alt: 'Imagen novedades',
		width: 940,
		height: 788,
		title: 'Novedades',
	},
	{
		src: '/images/informativas/personas_naturales_obligadas_a_declarar_renta.jpg',
		alt: 'Imagen personas naturales obligadas a declarar renta',
		width: 2000,
		height: 1414,
		title: 'Personas naturales obligadas a declarar renta',
	},
	{
		src: '/images/informativas/promedio_facturas_electrónicas.jpg',
		alt: 'Imagen promedio facturas electrónicas',
		width: 2000,
		height: 1414,
		title: 'Promedio facturas electrónicas',
	},
	{
		src: '/images/informativas/promedio_facturas_pos_.jpg',
		alt: 'Imagen promedio facturas POS',
		width: 2000,
		height: 1414,
		title: 'Promedio facturas POS',
	},
	{
		src: '/images/informativas/ransomware.jpg',
		alt: 'Imagen ransomware',
		width: 1080,
		height: 1080,
		title: 'Ransomware',
	},
	{
		src: '/images/informativas/restaurar_claves.jpg',
		alt: 'Imagen restaurar claves',
		width: 940,
		height: 788,
		title: 'Restaurar claves',
	},
	{
		src: '/images/informativas/sanciones_dian.jpg',
		alt: 'Imagen sanciones DIAN',
		width: 1414,
		height: 2000,
		title: 'Sanciones DIAN',
	},
];

export default gallery;
